<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Chris.png" />
    <None Remove="ShopUI\PlaceHolder.png" />
    <None Remove="Styles\Chris.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameData\GameData.csproj" />
    <ProjectReference Include="..\GameLibrary\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ShopUI\PlaceHolder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Styles\Chris.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Chris.png" />
  </ItemGroup>

</Project>
