<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="image.psd.png" />
    <None Remove="pixil-frame-0%281%29.png" />
    <None Remove="Player.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameData\GameData.csproj" />
    <ProjectReference Include="..\GameLibrary\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="image.psd.png" />
    <Resource Include="pixil-frame-0(1).png" />
    <Resource Include="Player.png" />
  </ItemGroup>

</Project>
