<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\ProtagonistSprites\chris.png" />
    <None Remove="Images\ShopItems\break.png" />
    <None Remove="Images\ShopItems\breakpoint.png" />
    <None Remove="Images\ShopItems\codeCompletion.png" />
    <None Remove="Images\ShopItems\completion.png" />
    <None Remove="Images\ShopItems\database.png" />
    <None Remove="Images\ShopItems\databasePOW.png" />
    <None Remove="Images\ShopItems\debugging.png" />
    <None Remove="Images\ShopItems\forLoop.png" />
    <None Remove="Images\ShopItems\linkedList.png" />
    <None Remove="Images\ShopItems\notepad.png" />
    <None Remove="Images\ShopItems\recurssion.png" />
    <None Remove="Images\ShopItems\vim.png" />
    <None Remove="Images\ShopItems\vsCode.png" />
    <None Remove="Items.txt" />
    <None Remove="ObjectData\AbilityNames.txt" />
    <None Remove="ObjectData\enemyNames.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\CreatureArt\OLD_DONOTUSE_pluscritters.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\CreatureArt\pluscritters.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\CreatureArt\scriptbeard.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\CreatureArt\javacup.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\CreatureArt\systemsnakes.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ProtagonistSprites\chris.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\break.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\breakpoint.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\codeCompletion.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\completion.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\database.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\databasePOW.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\debugging.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\forLoop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\linkedList.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\notepad.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\PlaceHolder.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ProtagonistSprites\nanon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ProtagonistSprites\vimmi.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\recurssion.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\vim.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\ShopItems\vsCode.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ObjectData\AbilityNames.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\CreatureArt\basher.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\CreatureArt\princesharp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ObjectData\EnemyNames.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
